### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by jediborre** [vibora-io/vibora#122]
Steps to reproduce
In Ubuntu 14
git clone https://github.com/vibora-io/vibora.git
python3.6 setup.py install

-----------------------------------------
running install
running bdist_egg
running egg_info
writing vibora.egg-info/PKG-INFO
writing dependency_links to vibora.egg-info/dependency_links.txt
writing requirements to vibora.egg-info/requires.txt
writing top-level names to vibora.egg-info/top_level.txt
reading manifest file 'vibora.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst' anywhere in distribution
warning: manifest_maker: MANIFEST.in, line 2: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'vibora.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'vibora.parsers.parser' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I. -I/git/vibora/vibora -I/usr/include/python3.6m -c vibora/parsers/parser.c -o build/temp.linux-x86_64-3.6/vibora/parsers/parser.o -O3
x86_64-linux-gnu-gcc: error: vibora/parsers/parser.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

**Comment by danieldaeschle** [comment]
You have to run `python3 build.py` first. For this you have to install several modules (on of them is cython).

**Comment by jediborre** [comment]
Where do I look for the modules I have to install?

Error compiling Cython file:
------------------------------------------------------------
...
#cython: language_level=3, boundscheck=False, wraparound=False

###############################################
# C IMPORTS
# noinspection PyUnresolvedReferences
from ..parsers.parser cimport HttpParser
^
------------------------------------------------------------

vibora/protocol/cprotocol.pxd:7:0: 'parsers.parser.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
        if not self.evaluated:
            self.eval()
        self.values[key.lower()] = value

    def __repr__(self):
        return f'<Headers {self.dump()}>'
               ^
------------------------------------------------------------

vibora/headers/headers.py:49:16: Syntax error in simple statement list

Error compiling Cython file:
------------------------------------------------------------
...
    cdef public str filename

    def __init__(self, filename=None):
        self.filename = filename

    async def save(self, str destination):
         ^
------------------------------------------------------------

vibora/multipart/parser.pyx:22:10: Syntax error in simple statement list

Error compiling Cython file:
------------------------------------------------------------
...
#!python
#cython: language_level=3

from . cimport cparser
      ^
------------------------------------------------------------

vibora/parsers/response.pxd:4:7: Relative cimport is not supported yet

Error compiling Cython file:
------------------------------------------------------------
...
# cython: language_level=3, boundscheck=False, wraparound=False, annotation_typing=False
import cython
# noinspection PyUnresolvedReferences
from ..headers.headers cimport Headers
^
------------------------------------------------------------

vibora/request/request.pxd:4:0: 'headers.headers.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
                     HttpParserInvalidStatusError,
                     HttpParserInvalidMethodError,
                     HttpParserInvalidURLError,
                     HttpParserUpgrade)
cimport cython
from ..parsers cimport cparser
^
------------------------------------------------------------

vibora/parsers/parser.pxd:16:0: 'parsers.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
import cython

############################################
# C IMPORTS
# noinspection PyUnresolvedReferences
from ..request.request cimport Request
^
------------------------------------------------------------

vibora/router/router.pxd:7:0: 'request.request.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
        validators = []
        for user_function in field.validators:
            if isinstance(user_function, staticmethod):
                user_function = user_function.__func__
            if isinstance(user_function, classmethod):
                raise SyntaxError(f'Class methods are not allowed as validators. ({user_function.__func__})')
                                  ^
------------------------------------------------------------

vibora/schemas/extensions/schemas.pyx:36:35: Expected ')', found 'BEGIN_STRING'

Error compiling Cython file:
------------------------------------------------------------
...
        self.default_callable = callable(self.default)

    cdef load(self, value):
        return value

    async def pipeline(self, value, context: dict):
         ^
------------------------------------------------------------

vibora/schemas/extensions/fields.pyx:21:10: Syntax error in simple statement list

Error compiling Cython file:
------------------------------------------------------------
...
                raise ValueError('You need to pass either builder or prebuilt param.')
            self.builder = builder
            self.cache_enabled = cache
            self.cache = prebuilt
        except KeyError:
            raise ValueError(f'Please type hint the return type of your function. ({builder})')
                             ^
------------------------------------------------------------

vibora/components/components.pyx:20:30: Expected ')', found 'BEGIN_STRING'

Error compiling Cython file:
------------------------------------------------------------
...
        self.app = app
        self.handler = handler
        self.loop = loop
        self.transport = transport

    cpdef void data_received(self, bytes data):
         ^
------------------------------------------------------------

vibora/protocol/cwebsocket.pyx:11:10: Return with value in void function

Error compiling Cython file:
------------------------------------------------------------
...
# cython: language_level=3, boundscheck=False, wraparound=False, annotation_typing=False

###################################################
# C IMPORTS
# noinspection PyUnresolvedReferences
from ..responses.responses cimport CachedResponse, Response
^
------------------------------------------------------------

vibora/cache/cache.pxd:6:0: 'responses.responses.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
#cython: language_level=3, boundscheck=False, wraparound=False
import cython

# C IMPORTS
# noinspection PyUnresolvedReferences
from ..protocol.cprotocol cimport Connection
^
------------------------------------------------------------

vibora/responses/responses.pxd:6:0: 'protocol.cprotocol.pxd' not found
Failed to compile .pyx files to C.

**Comment by jediborre** [comment]
Ended installing by 

apt-get install libpython3.6-dev   <------ the trick for me
pip install ujson
pip install vibora[fast]

:)

**Comment by danieldaeschle** [comment]
Yes, you need python 3.6

The version on pip isn't the newest. You can try to compile it now.

**Comment by felipebastosweb** [comment]
Hello, I need a help. Install instructions followed ...

* Install python3.6 -> ok
* sudo apt-get install cython3 -> ok (cython3)
* cd vibora/
* python3.6 build.py -> error

python3.6 build.py
Traceback (most recent call last):
  File "build.py", line 21, in <module>
    process = subprocess.run([cython] + list(pending_compilation) + ['--fast-fail'])
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/cython': '/usr/bin/cython'

If I install cython (sudo apt-get install cython) it will use Python 2.7 version. Look:

* sudo apt-get install cython
* python3.6 build.py -> error

python3.6 build.py

Error compiling Cython file:
------------------------------------------------------------
...
        """

        :return:
        """
        self.current_task.cancel()
        error = TimeoutError()
                           ^
------------------------------------------------------------

vibora/protocol/cprotocol.pyx:364:28: undeclared name not builtin: TimeoutError

Error compiling Cython file:
------------------------------------------------------------
...

    def __del__(self):
        if self.delete_on_exit is True:
            try:
                os.remove(self.temporary_path)
            except FileNotFoundError:
                                   ^
------------------------------------------------------------

vibora/multipart/parser.pyx:137:36: undeclared name not builtin: FileNotFoundError

Error compiling Cython file:
------------------------------------------------------------
...
        if not self.evaluated:
            self.eval()
        self.values[key.lower()] = value

    def __repr__(self):
        return f'<Headers {self.dump()}>'
               ^
------------------------------------------------------------

vibora/headers/headers.py:49:16: Syntax error in simple statement list

Error compiling Cython file:
------------------------------------------------------------
...
            return self.default_handlers[404]

    def check_integrity(self):
        for http_code in [404, 405]:
            if self.default_handlers.get(http_code) is None:
                raise NotImplementedError(f'Please implement the default {http_code} route.')
                                          ^
------------------------------------------------------------

vibora/router/router.py:233:43: Expected ')', found 'BEGIN_STRING'

Error compiling Cython file:
------------------------------------------------------------
...
                raise ValueError('You need to pass either builder or prebuilt param.')
            self.builder = builder
            self.cache_enabled = cache
            self.cache = prebuilt
        except KeyError:
            raise ValueError(f'Please type hint the return type of your function. ({builder})')
                             ^
------------------------------------------------------------

vibora/components/components.pyx:20:30: Expected ')', found 'BEGIN_STRING'
...

And ...

If I to install Cythoon usign pip3 .. cython3 is already installled.

* python3.6 -m pip install cython
Requirement already satisfied: cython in /usr/lib/python3/dist-packages (0.23.4)

I imagine that with Docker or virtualenv/pyenv working .. but, in O.S. enviroment fail.

I want that helpful.
