### ISSUE TITLE
first install successfully， but import error

### ISSUE THREAD

**Issue by rikewang** [vibora-io/vibora#126]
Traceback (most recent call last):
  File "D:/code/py/vibora_test/main.py", line 6, in <module>
    from vibora import Vibora
  File "C:\Program Files\Python36\lib\site-packages\vibora\__init__.py", line 7, in <module>
    from .server import *
  File "C:\Program Files\Python36\lib\site-packages\vibora\server.py", line 5, in <module>
    from signal import pause
ImportError: cannot import name 'pause'

**Comment by danieldaeschle** [comment]
Which version do you use? The version from PyPi? It is version 0.0.6 which contains a bug for windows. Version 0.0.7 on Github fixes this bug, but contains another import error (`from socket import SO_REUSEPORT`).

I would advise you to wait a little time for 0.1.0 and hope that it works on windows.

**Comment by rikewang** [comment]
signal.pause()
Cause the process to sleep until a signal is received; the appropriate handler will then be called. Returns nothing. Not on Windows. (See the Unix man page signal(2).)

some code not work well on windows, I modify some but endless?

**Comment by rikewang** [comment]
@danieldaeschle ye, I see it, But imcompatible code seem too many.

**Comment by kdebowski** [comment]
The newest version on repo (master branch) is fixed version. There is already issue opened for this error (https://github.com/vibora-io/vibora/issues/28). This is not connected with pip or python version. Signal.pause is just not supported on Windows.

**Comment by danieldaeschle** [comment]
@rikewang what does not work except of singal.pause()?
