### ISSUE TITLE
SyntaxError: invalid syntax -- self.async = iscoroutinefunction(handler) 

### ISSUE THREAD

**Issue by jakealstad** [vibora-io/vibora#16]
Attempting to run the example server code from the docs using Python 3.7.0b2 in pyenv on Mac OS 10.13.5. I haven't looked deep into the source yet but I am wondering if this is a known issue/incompatibility with Python 3.7.

**Comment by frnkvieira** [comment]
I was not aware of this issue, interesting... I'll push a fix tonight... I'll add Python 3.7 to the build pipeline so we can catch more of these... Thanks bro!

**Comment by jakealstad** [comment]
@frnkvieira No problem! If I wasn't at work I'd submit a PR myself :D

**Comment by johnpaulada** [comment]
How do we solve this? I'm still experiencing it 😔

**Comment by johnpaulada** [comment]
Oh the version at master works but the entry at PyPI isn't updated.

**Comment by bencagri** [comment]
yes. this occurs on python 3.7.

**Comment by IsaacDdR** [comment]
Any updates with this issue? 
Im still having this problem with Python 3.7 

>`Traceback (most recent call last):
  File "index.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
  File "/home/capcrunch/.local/lib/python3.7/site-packages/vibora/__init__.py", line 7, in <module>
    from .server import *
  File "/home/capcrunch/.local/lib/python3.7/site-packages/vibora/server.py", line 11, in <module>
    from .workers.handler import RequestHandler
  File "/home/capcrunch/.local/lib/python3.7/site-packages/vibora/workers/handler.py", line 7, in <module>
    from ..hooks import Events
  File "/home/capcrunch/.local/lib/python3.7/site-packages/vibora/hooks.py", line 38
    self.async = iscoroutinefunction(handler)
             ^
SyntaxError: invalid syntax
`

**Comment by isleifeng** [comment]
The same problem...

**Comment by RemiDesgrange** [comment]
https://docs.python.org/3/whatsnew/3.7.html => in 3.6, if you activate warning, it warn you about `async` and `await` being keyword also. In 3.7 `async` and `await` are not accepted as var name anymore. At this time vibora is not compatible with python 3.7

**Comment by gadepallivs** [comment]
I am using python 3.7.4 , and still get this error. Should i roll back to older version of the python ?
> File "C:\Users\user04\client-py\venv\lib\site-packages\beaker\synchronization.py", line 289
  self.async = 0
           ^

**Comment by vubon** [comment]
This bug is still existing Python 3.7 version. Anybody get a solution ? or need to downgrade Python version. thanks

**Comment by fbenavides69** [comment]
This bug is also present in Python 3.8 solutions?

Ubuntu 18.04
Python 3.8.1
Pyenv 1.2.16
PipEnv 2018.11.26



(async) fbenavides@x360:~/src/async$ python
Python 3.8.1 (default, Feb  2 2020, 02:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vibora
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fbenavides/.local/share/virtualenvs/async--osfTGhM/lib/python3.8/site-packages/vibora/__init__.py", line 7, in <module>
    from .server import *
  File "/home/fbenavides/.local/share/virtualenvs/async--osfTGhM/lib/python3.8/site-packages/vibora/server.py", line 11, in <module>
    from .workers.handler import RequestHandler
  File "/home/fbenavides/.local/share/virtualenvs/async--osfTGhM/lib/python3.8/site-packages/vibora/workers/handler.py", line 7, in <module>
    from ..hooks import Events
  File "/home/fbenavides/.local/share/virtualenvs/async--osfTGhM/lib/python3.8/site-packages/vibora/hooks.py", line 38
    self.async = iscoroutinefunction(handler)
         ^
SyntaxError: invalid syntax
>>>

**Comment by thehackercat** [comment]
any update?

**Comment by TacoBel42** [comment]
Any upd ?

**Comment by therumbler** [comment]
This is fixed in the vibora code on Github, but it hasn't been pushed to PyPI. If you really want it to work, install Vibora directly via git instead of PyPI

**Comment by ucodelukas** [comment]
?

**Comment by palaniyappanBala** [comment]
In Ubuntu,

1. sudo pip install cython3 (Install cython3)
2. git pull https://github.com/vibora-io/vibora.git
3. cd vibora
4. nano build.py: change the line _cython = os.path.join(os.path.dirname(sys.executable), 'cython')_ to  _cython = "cython"_
5. sudo python3 build.py
6. sudo python3 setup.py install
