### ISSUE TITLE
ImportError: cannot import name 'pause' from 'signal' (C:\Program Files\Python37\lib\signal.py)

### ISSUE THREAD

**Issue by juliosaraiva** [vibora-io/vibora#183]
(venv) PS D:\Python\vibora_test> python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vibora
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\vibora_test\venv\lib\site-packages\vibora\__init__.py", line 7, in <module>
    from .server import *
  File "D:\Python\vibora_test\venv\lib\site-packages\vibora\server.py", line 5, in <module>
    from signal import pause
ImportError: cannot import name 'pause' from 'signal' (C:\Program Files\Python37\lib\signal.py)

**Comment by pcdinh** [comment]
`signal.pause` does not work in Windows. The issue has been reported before https://github.com/vibora-io/vibora/issues/126

**Comment by alfuhigi** [comment]
`Traceback (most recent call last):
  File "server1.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
  File "C:\Users\abaja\.virtualenvs\tester-kWZRlKes\lib\site-packages\vibora\__init__.py", line 7, in <module>
    from .server import *
  File "C:\Users\abaja\.virtualenvs\tester-kWZRlKes\lib\site-packages\vibora\server.py", line 5, in <module>
    from signal import pause
ImportError: cannot import name 'pause' from 'signal' (c:\python37\Lib\signal.py)`

I am using pipenv and python 3.7.0

**Comment by impowski** [comment]
Have the same issue on Windows 10, tried Python 3.6.6 and Python 3.7

**Comment by Poule-magique** [comment]
Even worries, I downloaded python 3.6, the 3.7 and pipenv and always the same error.
I am under windows 10.

`ImportError: cannot import name 'pause' from 'signal' (c:\python37\Lib\signal.py)`

**Comment by marutichintan** [comment]
Me too same error

**Comment by Pebaz** [comment]
Library is not compatible with Windows due to not having `signal.pause`. Readme should be changed to reflect this.
