### ISSUE TITLE
debug=True seems to cause IndexError: string index out of range

### ISSUE THREAD

**Issue by davidtgq** [vibora-io/vibora#189]
When running debug=True, it seems Vibora is trying to print the client's IP, which somehow is causing this error for me:

```
Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 180, in vibora.protocol.cprotocol.Connection.handle_request
    new_response = await self.app.call_hooks(EVENTS_AFTER_ENDPOINT, self.components, route=route)
  File "/home/ubuntu/src/api/vibora/application.py", line 101, in call_hooks
    response = await listener.call_handler(components)
  File "/home/ubuntu/src/api/vibora/server.py", line 277, in access_logs
    print(format_access_log(request, response), file=sys.stderr)
  File "/home/ubuntu/src/api/vibora/utils.py", line 192, in format_access_log
    f"{request.client_ip()} - "
  File "vibora/request/request.pyx", line 124, in vibora.request.request.Request.client_ip
    cpdef str client_ip(self):
  File "vibora/request/request.pyx", line 125, in vibora.request.request.Request.client_ip
    return self.protocol.client_ip()
  File "vibora/protocol/cprotocol.pyx", line 412, in vibora.protocol.cprotocol.Connection.client_ip
    return self.transport.get_extra_info('peername')[0]
IndexError: string index out of range

```

**To Reproduce**
1. Enable debug mode
2. Visit any endpoint
3. Vibora will try to print `{ip} - {method} {url} - {status} - {user-agent}`
4. See error when it tries to get the ip

**Additional context**
Ubuntu 18.04 server, gcc 7.3.0, master branch

I tried removing the `[0]` and running `build.py` again which resulted in the same error

(PS while I'm here, I'm assuming it's safe to build.py again and again without removing any previous files, right?)

**Comment by davidtgq** [comment]
This was a local issue, fixed by deleting and downloading/building from scratch
