### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jie-Yuan** [vibora-io/vibora#227]
![image](https://user-images.githubusercontent.com/20265321/50504118-6103d200-0aa6-11e9-9353-08a39ace62eb.png)

**Comment by jenriquez-techempower** [comment]
Having the same issue. It responds to query strings with 404 responses.

**Comment by dmitry-saritasa** [comment]
Same effect

**Comment by bryant-sharethis** [comment]
how was this not fixed yet? querystrings seem to be unusable...

```
from vibora import Vibora, Response, Request

app = Vibora()

@app.route('/')
async def home(request: Request):
    print(request.args)
    return Response(f'Name: {request.args['name']}'.encode())
if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000)
```
```
# Vibora (0.0.6) # http://0.0.0.0:8000
<vibora.utils.RequestParams object at 0x1069b67b8>
Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 152, in vibora.protocol.cprotocol.Connection.handle_request
  File "test-vibora2.py", line 8, in home
    return Response(f"Name: {request.args['name']}".encode())
  File "/Users/bryant/.pyenv/versions/3.6.9/lib/python3.6/site-packages/vibora/utils.py", line 40, in __getitem__
    return self.values[item]
KeyError: 'name'
```

Is there an undocumented way to configure Vibora that fixes this?
