### ISSUE TITLE
Lot of problems with Pycharm as well, and the whole library, OS ubuntu

### ISSUE THREAD

**Issue by clust3rsekt0r** [vibora-io/vibora#229]
Traceback (most recent call last):
  File "/home/clust3r/Documents/pyprojects/untitled/konohaserv.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
  File "/home/clust3r/Documents/pyprojects/untitled/lib/python3.7/site-packages/vibora/__init__.py", line 7, in <module>
    from .server import *
  File "/home/clust3r/Documents/pyprojects/untitled/lib/python3.7/site-packages/vibora/server.py", line 11, in <module>
    from .workers.handler import RequestHandler
  File "/home/clust3r/Documents/pyprojects/untitled/lib/python3.7/site-packages/vibora/workers/handler.py", line 7, in <module>
    from ..hooks import Events
  File "/home/clust3r/Documents/pyprojects/untitled/lib/python3.7/site-packages/vibora/hooks.py", line 38
    self.async = iscoroutinefunction(handler)
             ^
SyntaxError: invalid syntax

**Comment by TheScottishFly** [comment]
All you need to do is edit :

hooks.py line 38:
self.async -> self.is_async

blueprints.py line 172
[...] if hook.async -> [...] if hook.is_async

And normally, it works :)
