### ISSUE TITLE
How can I use vibora to build a https server

### ISSUE THREAD

**Issue by yumoqing** [vibora-io/vibora#244]
Vibora is great fast, But I search documents of it, can not found any guide to setup vibora as a https server

Any one can guide me there

Thanks

**Comment by yumoqing** [comment]
I made such try:

=====code begin=====

import socket
import ssl

def openSslSock(host,port,cert,key):
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM, 0)
        sock.bind((host,port))
        sock.listen(5)
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(cert,key)
        ssock = context.wrap_socket(sock,server_side=True)
        return ssock           

======code end======

and:


        ssock = None
        if config.website.get('ssl',False):
                ssock = openSslSock(
                                config.website.host,
                                config.website.port,
                                config.website.ssl.crtfile,
                                config.website.ssl.keyfile)
        app.run(debug=config.debug,
                host=config.website.host,
                port=config.website.port,
                sock=ssock)

But it is failed to work, the error mesages are:

Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 298, in vibora.protocol.cprotocol.Connection.data_received
  File "vibora/parsers/parser.pyx", line 145, in vibora.parsers.parser.HttpParser.feed_data
vibora.parsers.errors.HttpParserInvalidMethodError: invalid HTTP method
Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 298, in vibora.protocol.cprotocol.Connection.data_received
  File "vibora/parsers/parser.pyx", line 145, in vibora.parsers.parser.HttpParser.feed_data
vibora.parsers.errors.HttpParserInvalidMethodError: invalid HTTP method
Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 298, in vibora.protocol.cprotocol.Connection.data_received
  File "vibora/parsers/parser.pyx", line 145, in vibora.parsers.parser.HttpParser.feed_data
vibora.parsers.errors.HttpParserInvalidMethodError: invalid HTTP method
