### ISSUE TITLE
How template pages reference static files

### ISSUE THREAD

**Issue by XZHhengge** [vibora-io/vibora#246]
├── helloworld.py
├── static
│   ├── css
│   ├── images
│   └── js
├── templates
│   └── index.html

```
app = Vibora(
    template_dirs=['.'],
    static=StaticHandler(paths=['.'],
    host='127.0.0.1',
    )
)

@app.route('/index')
async def index():
    return await app.render('index.html')
```

index.html
`<img src="/static/images/bms.png" class="img-responsive center-block"/>
`
the Traceback like this
```
Traceback (most recent call last):
  File "vibora/protocol/cprotocol.pyx", line 152, in vibora.protocol.cprotocol.Connection.handle_request
  File "/home/perfectman/PycharmProjects/firstvibora/venv/lib/python3.6/site-packages/vibora/static.py", line 149, in handle
    raise StaticNotFound()
vibora.exceptions.StaticNotFound
[2019-04-26T22:29:24+08:00] - 127.0.0.1 - "GET /static/images/bms.png" - 500 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
```
Can someone help me with this problem?

**Comment by yumoqing** [comment]
try this one [viboraserver](https://github.com/yumoqing/viboraserver)

**Comment by XZHhengge** [comment]
> try this one [viboraserver](https://github.com/yumoqing/viboraserver)

**Comment by XZHhengge** [comment]
> 试试这个[viboraserver](https://github.com/yumoqing/viboraserver)

I saw your project,It's very complicated for me,but I try it.I have so many other questions, Can you leave behind a contact way? LIke a WeChat?

**Comment by XZHhengge** [comment]
I solve this question finally.But I met the reference media 404 and The static files name contains Chinese characters also 404.

**Comment by yumoqing** [comment]
safecorner find this we chat id发自我的华为手机-------- 原始邮件 --------主题：Re: [vibora-io/vibora] How template pages reference static files (#246)发件人：cmzz 收件人：vibora-io/vibora 抄送：yumoqing ,Comment 

试试这个viboraserver



I saw your project,It's very complicated for me,but I try it.I have so many other questions, Can you leave behind a contact way? LIke a WeChat?
