### ISSUE TITLE
ImportError: cannot import name 'pause'

### ISSUE THREAD

**Issue by littleningmeng** [vibora-io/vibora#260]
>>> from vibora import Vibora, JsonResponse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Develop\Python3.6.8\lib\site-packages\vibora\__init__.py", line 7, in <module>
    from .server import *
  File "C:\Develop\Python3.6.8\lib\site-packages\vibora\server.py", line 5, in <module>
    from signal import pause

**Comment by littleningmeng** [comment]
C:\Users\apache\Desktop>python -m pip install vibora
Requirement already satisfied: vibora in c:\develop\python3.6.8\lib\site-packages (0.0.6)
Requirement already satisfied: pendulum in c:\develop\python3.6.8\lib\site-packages (from vibora) (2.0.5)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in c:\develop\python3.6.8\lib\site-packages (from pendulum->vibora) (2.8.1)
Requirement already satisfied: pytzdata>=2018.3 in c:\develop\python3.6.8\lib\site-packages (from pendulum->vibora) (2019.3)
Requirement already satisfied: six>=1.5 in c:\develop\python3.6.8\lib\site-packages (from python-dateutil<3.0,>=2.6->pendulum->vibora) (1.12.0)

**Comment by Pebaz** [comment]
`signal.pause` is not included in the Python standard library on Windows.
