### ISSUE TITLE
I can't install from pip - windows10  python 3.6 32bits 

### ISSUE THREAD

**Issue by rhazz** [vibora-io/vibora#261]
**Describe the bug**

I can't install from pip - windows10  python 3.6 32bits 
pip install vibora

**Expected behavior**
 install

**Screenshots**

C:\TEMP\python>pip install vibora==0.0.6
Looking in indexes: http://binario.baixa:8081/repository/pypi-repo/simple/
Collecting vibora==0.0.6
  Downloading http://binario.baixa:8081/repository/pypi-repo/packages/1c/db/c42998b106b89d67ce0fe256320454ca224e4d3d05f56dd518514a5b738c/vibora-0.0.6.tar.gz (1.1 MB)
     |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 1.1 MB 1.1 MB/s
Requirement already satisfied: pendulum in c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages (from vibora==0.0.6) (2.0.5)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages (from pendulum->vibora==0.0.6) (2.8.1)
Requirement already satisfied: pytzdata>=2018.3 in c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages (from pendulum->vibora==0.0.6) (2019.3)
Requirement already satisfied: six>=1.5 in c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages (from python-dateutil<3.0,>=2.6->pendulum->vibora==0.0.6) (1.14.0)
Installing collected packages: vibora
    Running setup.py install for vibora ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sofredorDoPython\\AppData\\Local\\Temp\\pip-install-13f1kiud\\vibora\\setup.py'"'"'; __file__='"'"'C:\\Users\\sofredorDoPython\\AppData\\Local\\Temp\\pip-install-13f1kiud\\vibora\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sofredorDoPython\AppData\Local\Temp\pip-record-65j4vhod\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\Include\vibora'
         cwd: C:\Users\sofredorDoPython\AppData\Local\Temp\pip-install-13f1kiud\vibora\
    Complete output (185 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\tests
    copying tests\blueprints.py -> build\lib.win32-3.6\tests
    copying tests\cache.py -> build\lib.win32-3.6\tests
    copying tests\components.py -> build\lib.win32-3.6\tests
    copying tests\exceptions.py -> build\lib.win32-3.6\tests
    copying tests\forms.py -> build\lib.win32-3.6\tests
    copying tests\headers.py -> build\lib.win32-3.6\tests
    copying tests\helpers.py -> build\lib.win32-3.6\tests
    copying tests\hooks.py -> build\lib.win32-3.6\tests
    copying tests\limits.py -> build\lib.win32-3.6\tests
    copying tests\responses.py -> build\lib.win32-3.6\tests
    copying tests\streaming.py -> build\lib.win32-3.6\tests
    copying tests\subdomains.py -> build\lib.win32-3.6\tests
    copying tests\timeouts.py -> build\lib.win32-3.6\tests
    copying tests\__init__.py -> build\lib.win32-3.6\tests
    creating build\lib.win32-3.6\vibora
    copying vibora\application.py -> build\lib.win32-3.6\vibora
    copying vibora\blueprints.py -> build\lib.win32-3.6\vibora
    copying vibora\constants.py -> build\lib.win32-3.6\vibora
    copying vibora\context.py -> build\lib.win32-3.6\vibora
    copying vibora\cookies.py -> build\lib.win32-3.6\vibora
    copying vibora\exceptions.py -> build\lib.win32-3.6\vibora
    copying vibora\hooks.py -> build\lib.win32-3.6\vibora
    copying vibora\limits.py -> build\lib.win32-3.6\vibora
    copying vibora\optimizer.py -> build\lib.win32-3.6\vibora
    copying vibora\server.py -> build\lib.win32-3.6\vibora
    copying vibora\static.py -> build\lib.win32-3.6\vibora
    copying vibora\tests.py -> build\lib.win32-3.6\vibora
    copying vibora\utils.py -> build\lib.win32-3.6\vibora
    copying vibora\__init__.py -> build\lib.win32-3.6\vibora
    copying vibora\__version__.py -> build\lib.win32-3.6\vibora
    creating build\lib.win32-3.6\tests\client
    copying tests\client\external.py -> build\lib.win32-3.6\tests\client
    copying tests\client\interface.py -> build\lib.win32-3.6\tests\client
    copying tests\client\keep_alive.py -> build\lib.win32-3.6\tests\client
    copying tests\client\multipart.py -> build\lib.win32-3.6\tests\client
    copying tests\client\ssl_connections.py -> build\lib.win32-3.6\tests\client
    copying tests\client\streaming.py -> build\lib.win32-3.6\tests\client
    copying tests\client\__init__.py -> build\lib.win32-3.6\tests\client
    creating build\lib.win32-3.6\tests\router
    copying tests\router\prefixes.py -> build\lib.win32-3.6\tests\router
    copying tests\router\strategies.py -> build\lib.win32-3.6\tests\router
    copying tests\router\__init__.py -> build\lib.win32-3.6\tests\router
    creating build\lib.win32-3.6\tests\templates
    copying tests\templates\exceptions.py -> build\lib.win32-3.6\tests\templates
    copying tests\templates\extensions.py -> build\lib.win32-3.6\tests\templates
    copying tests\templates\integration.py -> build\lib.win32-3.6\tests\templates
    copying tests\templates\nodes.py -> build\lib.win32-3.6\tests\templates
    copying tests\templates\__init__.py -> build\lib.win32-3.6\tests\templates
    creating build\lib.win32-3.6\vibora\cache
    copying vibora\cache\cache.py -> build\lib.win32-3.6\vibora\cache
    copying vibora\cache\__init__.py -> build\lib.win32-3.6\vibora\cache
    creating build\lib.win32-3.6\vibora\client
    copying vibora\client\connection.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\decoders.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\defaults.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\exceptions.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\limits.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\pool.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\request.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\response.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\retries.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\session.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\websocket.py -> build\lib.win32-3.6\vibora\client
    copying vibora\client\__init__.py -> build\lib.win32-3.6\vibora\client
    creating build\lib.win32-3.6\vibora\components
    copying vibora\components\__init__.py -> build\lib.win32-3.6\vibora\components
    creating build\lib.win32-3.6\vibora\headers
    copying vibora\headers\headers.py -> build\lib.win32-3.6\vibora\headers
    copying vibora\headers\__init__.py -> build\lib.win32-3.6\vibora\headers
    creating build\lib.win32-3.6\vibora\multipart
    copying vibora\multipart\containers.py -> build\lib.win32-3.6\vibora\multipart
    copying vibora\multipart\__init__.py -> build\lib.win32-3.6\vibora\multipart
    creating build\lib.win32-3.6\vibora\parsers
    copying vibora\parsers\errors.py -> build\lib.win32-3.6\vibora\parsers
    copying vibora\parsers\typing.py -> build\lib.win32-3.6\vibora\parsers
    copying vibora\parsers\__init__.py -> build\lib.win32-3.6\vibora\parsers
    creating build\lib.win32-3.6\vibora\protocol
    copying vibora\protocol\definitions.py -> build\lib.win32-3.6\vibora\protocol
    copying vibora\protocol\__init__.py -> build\lib.win32-3.6\vibora\protocol
    creating build\lib.win32-3.6\vibora\request
    copying vibora\request\__init__.py -> build\lib.win32-3.6\vibora\request
    creating build\lib.win32-3.6\vibora\responses
    copying vibora\responses\responses.py -> build\lib.win32-3.6\vibora\responses
    copying vibora\responses\__init__.py -> build\lib.win32-3.6\vibora\responses
    creating build\lib.win32-3.6\vibora\router
    copying vibora\router\parser.py -> build\lib.win32-3.6\vibora\router
    copying vibora\router\router.py -> build\lib.win32-3.6\vibora\router
    copying vibora\router\__init__.py -> build\lib.win32-3.6\vibora\router
    creating build\lib.win32-3.6\vibora\schemas
    copying vibora\schemas\exceptions.py -> build\lib.win32-3.6\vibora\schemas
    copying vibora\schemas\messages.py -> build\lib.win32-3.6\vibora\schemas
    copying vibora\schemas\schemas.py -> build\lib.win32-3.6\vibora\schemas
    copying vibora\schemas\types.py -> build\lib.win32-3.6\vibora\schemas
    copying vibora\schemas\__init__.py -> build\lib.win32-3.6\vibora\schemas
    creating build\lib.win32-3.6\vibora\sessions
    copying vibora\sessions\base.py -> build\lib.win32-3.6\vibora\sessions
    copying vibora\sessions\client.py -> build\lib.win32-3.6\vibora\sessions
    copying vibora\sessions\file.py -> build\lib.win32-3.6\vibora\sessions
    copying vibora\sessions\redis.py -> build\lib.win32-3.6\vibora\sessions
    copying vibora\sessions\__init__.py -> build\lib.win32-3.6\vibora\sessions
    creating build\lib.win32-3.6\vibora\templates
    copying vibora\templates\ast.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\cache.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\engine.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\exceptions.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\extensions.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\loader.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\nodes.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\parser.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\template.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\utils.py -> build\lib.win32-3.6\vibora\templates
    copying vibora\templates\__init__.py -> build\lib.win32-3.6\vibora\templates
    creating build\lib.win32-3.6\vibora\websockets
    copying vibora\websockets\obj.py -> build\lib.win32-3.6\vibora\websockets
    copying vibora\websockets\__init__.py -> build\lib.win32-3.6\vibora\websockets
    creating build\lib.win32-3.6\vibora\workers
    copying vibora\workers\handler.py -> build\lib.win32-3.6\vibora\workers
    copying vibora\workers\necromancer.py -> build\lib.win32-3.6\vibora\workers
    copying vibora\workers\reaper.py -> build\lib.win32-3.6\vibora\workers
    copying vibora\workers\__init__.py -> build\lib.win32-3.6\vibora\workers
    creating build\lib.win32-3.6\vibora\schemas\extensions
    copying vibora\schemas\extensions\__init__.py -> build\lib.win32-3.6\vibora\schemas\extensions
    creating build\lib.win32-3.6\vibora\templates\compilers
    copying vibora\templates\compilers\base.py -> build\lib.win32-3.6\vibora\templates\compilers
    copying vibora\templates\compilers\cython.py -> build\lib.win32-3.6\vibora\templates\compilers
    copying vibora\templates\compilers\helpers.py -> build\lib.win32-3.6\vibora\templates\compilers
    copying vibora\templates\compilers\python.py -> build\lib.win32-3.6\vibora\templates\compilers
    copying vibora\templates\compilers\__init__.py -> build\lib.win32-3.6\vibora\templates\compilers
    running build_ext
    building 'vibora.parsers.parser' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sofredorDoPython\AppData\Local\Temp\pip-install-13f1kiud\vibora\setup.py", line 118, in <module>
        packages=find_packages()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\command\build_ext.py", line 205, in build_extension
        _build_ext.build_extension(self, ext)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\command\build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\site-packages\setuptools\msvc.py", line 1620, in return_env
        if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
      File "c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\lib\genericpath.py", line 30, in isfile
        st = os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sofredorDoPython\\AppData\\Local\\Temp\\pip-install-13f1kiud\\vibora\\setup.py'"'"'; __file__='"'"'C:\\Users\\sofredorDoPython\\AppData\\Local\\Temp\\pip-install-13f1kiud\\vibora\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sofredorDoPython\AppData\Local\Temp\pip-record-65j4vhod\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\sofredorDoPython\appdata\local\programs\python\python36-32\Include\vibora' Check the logs for full command output.

**Comment by rhazz** [comment]
I reinstalled the libraries and it worked
