### ISSUE TITLE
ImportError: cannot import name 'SO_REUSEPORT' from 'socket' || SyntaxError: invalid syntax in "self.async = iscoroutinefunction(handler)"

### ISSUE THREAD

**Issue by David-Lor** [vibora-io/vibora#269]
**Environment:**

- Ubuntu 18.04 bionic x86_64 Linux 4.15.0-136-generic
- Tried on Python 3.7.10 & Python 3.8.8 - using miniconda virtual environments (conda 4.9.2)

**Code snippet used:**

```python
from vibora import Vibora, JsonResponse

app = Vibora()

@app.route('/')
async def home():
    return JsonResponse({'hello': 'world'})

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000)
```

**Steps to reproduce:**

1. pip install vibora[fast]
```bash
$ pip install vibora[fast]
Collecting vibora[fast]
  Using cached vibora-0.0.6-cp38-cp38-linux_x86_64.whl
WARNING: vibora 0.0.6 does not provide the extra 'fast'
Collecting ujson
  Using cached ujson-4.0.2-cp38-cp38-manylinux1_x86_64.whl (181 kB)
Collecting pendulum
  Using cached pendulum-2.1.2-cp38-cp38-manylinux1_x86_64.whl (155 kB)
Collecting uvloop
  Using cached uvloop-0.15.2-cp38-cp38-manylinux2010_x86_64.whl (4.7 MB)
Collecting pytzdata>=2020.1
  Using cached pytzdata-2020.1-py2.py3-none-any.whl (489 kB)
Collecting python-dateutil<3.0,>=2.6
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: six>=1.5 in /home/david/.local/lib/python3.8/site-packages (from python-dateutil<3.0,>=2.6->pendulum->vibora[fast]) (1.14.0)
Installing collected packages: pytzdata, python-dateutil, uvloop, ujson, pendulum, vibora
Successfully installed pendulum-2.1.2 python-dateutil-2.8.1 pytzdata-2020.1 ujson-4.0.2 uvloop-0.15.2 vibora-0.0.6
```

2. Run the code snippet
```bash
$ python test_vibora.py
Traceback (most recent call last):
  File "test_vibora.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/__init__.py", line 7, in <module>
    from .server import *
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/server.py", line 11, in <module>
    from .workers.handler import RequestHandler
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/workers/handler.py", line 3, in <module>
    from socket import IPPROTO_TCP, TCP_NODELAY, SO_REUSEADDR, SOL_SOCKET, SO_REUSEPORT, socket
ImportError: cannot import name 'SO_REUSEPORT' from 'socket' (/home/david/.miniconda3/envs/python-vibora/lib/python3.8/socket.py)
```

3. Try the workaround proposed in https://github.com/vibora-io/vibora/issues/79#issuecomment-406616861
```python
import socket
socket.SO_REUSEPORT = 15

from vibora import Vibora, JsonResponse

app = Vibora()

@app.route('/')
async def home():
    return JsonResponse({'hello': 'world'})

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8000)
```

4. Run the code snippet with the workaround
```bash
$ python test_vibora.py
Traceback (most recent call last):
  File "test_vibora.py", line 4, in <module>
    from vibora import Vibora, JsonResponse
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/__init__.py", line 7, in <module>
    from .server import *
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/server.py", line 11, in <module>
    from .workers.handler import RequestHandler
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/workers/handler.py", line 7, in <module>
    from ..hooks import Events
  File "/home/david/.miniconda3/envs/python-vibora/lib/python3.8/site-packages/vibora/hooks.py", line 38
    self.async = iscoroutinefunction(handler)
         ^
SyntaxError: invalid syntax
```

Related issues: #79 #228 #106

**Comment by CaptainDestructo** [comment]
Supposedly this is fixed by using the code from GitHub directly. The pip repo is outdated.
