### ISSUE TITLE
Issues setting cookies when using Cookie()

### ISSUE THREAD

**Issue by Jarmahent** [vibora-io/vibora#40]
```python
    @app.route('/setcookie")
    async def example_setcookie():
        cookies = [Cookie('test', 'testcookie')]
        return JsonResponse({"works": "Works"}, cookies=cookies)
```
Throws an error coming from the Cookie class when `.encode()` is called in the [header function](https://github.com/vibora-io/vibora/blob/master/vibora/cookies.py#L45). 
Exact Error: 
```console

Traceback (most recent call last):
  File "vibora/responses/responses.py", line 102, in vibora.responses.responses.Response.encode
TypeError: can't concat str to bytes
Exception ignored in: 'vibora.responses.responses.Response.send'
Traceback (most recent call last):
  File "vibora/responses/responses.py", line 102, in vibora.responses.responses.Response.encode
TypeError: can't concat str to bytes
```

**Comment by dukkee** [comment]
see #59
