### ISSUE TITLE
example run failed after install on windows

### ISSUE THREAD

**Issue by xiaomingdaily** [vibora-io/vibora#64]
D:\vibora>python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
  File "D:\Python36\lib\site-packages\vibora\__init__.py", line 7, in <module>
    from .server import *
  File "D:\Python36\lib\site-packages\vibora\server.py", line 5, in <module>
    from signal import pause
ImportError: cannot import name 'pause'

**Comment by frnkvieira** [comment]
As you can see on other issues, Windows support is in-progress. Thanks!
