### ISSUE TITLE
cannot import name 'JsonResponse'

### ISSUE THREAD

**Issue by coolgrass** [vibora-io/vibora#87]
I used step by step this introduction https://docs.vibora.io/docs/, but in the end i have got
```
Traceback (most recent call last):
  File "/Users/cgrass/Work/MMS/server/anything.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
ImportError: cannot import name 'JsonResponse'
```
mac os High Sierra , Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)

**Comment by HongYuzhuang** [comment]
Hi,
    I met same Error ,This Could be Addressed manually by editing __init__.py of Vibora and adding line 'import * from response'  to it .
On 6/27/2018 15:30，Cgrass<notifications@github.com> wrote：

I used step by step this introduction https://docs.vibora.io/docs/, but in the end i have got

Traceback (most recent call last):
  File "/Users/cgrass/Work/MMS/server/anything.py", line 1, in <module>
    from vibora import Vibora, JsonResponse
ImportError: cannot import name 'JsonResponse'


mac os High Sierra , Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31)

**Comment by dukkee** [comment]
Oh, docs aren't correct currently. Read please repo README, it's more actual
