### ISSUE TITLE
Unhandled exception in event loop.

### ISSUE THREAD

**Issue by avilior** [vibora-io/vibora#89]
**Describe the bug**
While running a simple GET example I get periodic Unhandled exception in event loop.

**To Reproduce**
 Nothing special execute many GET requests and wait.

**Expected behavior**
I don't expect in this situation to get an exception. But if I do I expect it to be handled.

**Screenshots**

Unhandled exception in event loop
Traceback (most recent call last):
  File "uvloop/handles/streamserver.pyx", line 135, in uvloop.loop.__uv_streamserver_on_listen
  File "uvloop/handles/streamserver.pyx", line 77, in uvloop.loop.UVStreamServer._on_listen
  File "uvloop/handles/stream.pyx", line 244, in uvloop.loop.UVStream._accept
  File "uvloop/handles/basetransport.pyx", line 49, in uvloop.loop.UVBaseTransport._fatal_error
OSError: [Errno 22] Invalid argument

**Additional context**

**Comment by frnkvieira** [comment]
Please uninstall uvloop (pip3 uninstall uvloop) and check if the same occurs with asyncio loop, in case the error is still present please copy the stack trace here to help me understand what's going on.

**Comment by avilior** [comment]
Overtaken by events
